---
- hosts: all
  become: yes
  
  tasks:
  
  - name: install docker with zypper
    zypper:
      name: docker
      state: present

  - name: Ensure docker-service is started
    service: 
      name: docker 
      state: restarted